version: "3.9"
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./apps/backend/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGODB_URI=mongodb://mongo:27017
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./apps/frontend/Dockerfile
  #   ports:
  #     - "4000:80"
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
#   mongo:
#     image: mongo:6
#     restart: always
#     volumes:
#       - mongo-data:/data/db
#     ports:
#       - '27017:27017'
#   redis:
#     image: redis:7
#     ports:
#       - '6379:6379'
#     volumes:
#       - redis-data:/data

# volumes:
#   mongo-data:
#   redis-data:
