export const CAMPAIGN_QUEUE_NAME = 'campaign';

export enum CAMPAIGN_QUEUE_JOB_NAMES {
  START_CAMPAIGN = 'START_CAMPAIGN',
  NEXT_CAMPAIGN = 'NEXT_CAMPAIGN',
  FINISH_CAMPAIGN = 'FINISH_CAMPAIGN',
}
